dockermgt:
  image: dngroup/simu-dockermgt
  ports:
   - "127.0.0.1:9001:9001"
  volumes:
   - /tmp/datatemu/:/tmp/datatemu/
sessionmgt:
  image: dngroup/simu-sessionmgt
  ports:
   - "127.0.0.1:9000:9000"
  links:
   - dockermgt
  volumes:
   - /tmp/datatemu/:/tmp/datatemu/
  env_file:
        - application.env
server:
  image: dngroup/simu-serverapache
  ports:
   - "127.0.0.1:9002:80"
  cap_add:
   - NET_ADMIN
  volumes:
   - ../input:/usr/local/apache2/htdocs/
apache:
  image: dngroup/simu-serverapache
  ports:
   - "127.0.0.1:9003:80"
  cap_add:
   - NET_ADMIN
  volumes:
   - ../input:/usr/local/apache2/htdocs/
