
spring:
  application:
    name: temudemo
  datasource:
    url: jdbc:h2:mem:sessionsimu;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
  h2: 
    console: 
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  jersey:
      type: servlet
security:
  basic:
    enabled: false
    
server:
    port: 9000
    
